main:   main.o  quick_sort.o
            gcc -o  main    main.o    quick_sort.o

main.o: main.c  quick_sort.h
            gcc -c  main.c

quick_sort.o:   quick_sort.c    quick_sort.h
            gcc -c  quick_sort.c
